#include<stdio.h>
int main()
{
    int n,i,c=0,t,m,b;
    scanf("%d",&n);
    int a[i];
    for(i=0;i<n;i++)
    {
        scanf("%d",&a[i]);
    }
    for(i=00;i<n;i++)
    {
        if(i!=0&&i!=(n-1))
        {
            if(a[i-1]%2==0&&a[i+1]!=0||a[i-1]%2!=0&&a[i+1]==0)
            {
                c++;
            }
        }
    }
    b=c;
    for(i=0;i<n;i++)
    {
        if(a[n-1]%2==0&a[1]%2!=0||a[n-1]%2!=0&a[1]%2==0)
        {
            t=1;
        }
        else
        {
            t=0;
        }
    }
    for(i=0;i<n;i++)
    {
        if(a[n-2]%2==0&a[0]%2!=0||a[n-2]%2!=0&a[0]%2==0)
        {
            m=1;
        }
        else
        {
            m=0;
        }
    }
    printf("%d",(b+t+m));
}
